version: '3.3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:${ELK_VERSION}
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    stdin_open: true
    tty: true
    # network_mode: host
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '50'
    networks:
      - elk
  # kibana:
  #   container_name: kibana
  #   image: kibana:${ELK_VERSION}
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - 5601:5601
  #   links:
  #     - elasticsearch:elasticsearch
  #   depends_on:
  #     - elasticsearch
  #   stdin_open: true
  #   tty: true
  #   # network_mode: bridge
  #   logging:
  #     driver: 'json-file'
  #     options:
  #       max-size: '10m'
  #       max-file: '50'
  #   networks:
  #     - elk
  logstash:
    container_name: logstash
    # network_mode: host
    image: logstash:${ELK_VERSION}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elk/configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk/configs/logstash.template.json:/usr/share/logstash/templates/logstash.template.json
    ports:
      - 5044:5044
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '50'
    networks:
      - elk
  filebeat:
    user: root
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    links:
      - logstash:logstash
    depends_on:
      - logstash
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - ./elk/filebeat/mylog:/usr/share/filebeat/mylog
      - ./elk/configs/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: ['--strict.perms=false']
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    # network_mode: host
    deploy:
      mode: global
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '50'
    networks:
      - elk
  # nats-streaming:
  #   image: 'nats-streaming:0.17.0'
  #   container_name: nats
  #   # network_mode: bridge
  #   command:
  #     - '--port'
  #     - '4222'
  #     - '--http_port'
  #     - '8222'
  #     - '--hb_interval'
  #     - '5s'
  #     - '--hb_timeout'
  #     - '5s'
  #     - '--hb_fail_count'
  #     - '2'
  #     - '--stan_debug'
  #     - '--cluster_id'
  #     - 'tts'
  #   ports:
  #     - '4222:4222'
  #     - '8222:8222'
  #   # volumes:
  #   #   - './nats-streaming:/data'
networks:
  elk:
    driver: bridge
