version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    stdin_open: true
    tty: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '50'
    networks:
      - tts
  kibana:
    image: kibana:${ELK_VERSION}
    container_name: kibana
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '50'
    networks:
      - tts
  logstash:
    image: logstash:${ELK_VERSION}
    container_name: logstash
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - $PWD/configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - $PWD/configs/logstash.template.json:/usr/share/logstash/templates/logstash.template.json
    ports:
      - 5044:5044
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '50'
    networks:
      - tts
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - '$PWD/data/mongodb-data:/data/db:z'
      - '$PWD/configs/mongod.conf:/etc/mongod.conf:z'
    networks:
      - tts
  redis:
    image: 'redis:alpine'
    container_name: redis
    command: redis-server --requirepass ${REDIS_SERVER_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - '$PWD/data/redis-data:/var/lib/redis:z'
      - '$PWD/redis.conf:/usr/local/etc/redis/redis.conf:z'
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - tts
  nats-streaming:
    image: 'nats-streaming:0.17.0'
    container_name: nats-streaming
    command:
      - '--port'
      - '4222'
      - '--http_port'
      - '8222'
      - '--hb_interval'
      - '5s'
      - '--hb_timeout'
      - '5s'
      - '--hb_fail_count'
      - '2'
      - '--stan_debug'
      - '--cluster_id'
      - 'tts'
    ports:
      - '4222:4222'
      - '8222:8222'
    volumes:
      - '$PWD/data/nats-streaming:/data'
    networks:
      - tts
  tts_static:
    image: 'viethung512/tts_static:latest'
    container_name: tts_static
    ports:
      - '3001:3001'
    volumes:
      - '$PWD/data/tts_static:/app/public'
    networks:
      - tts

networks:
  tts:
    driver: bridge
