apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s-dev/*

build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: vbee-tts-297514
  artifacts:
    # - image: viethung512/tts_auth
    - image: us.gcr.io/vbee-tts-297514/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: viethung512/tts_data
    - image: us.gcr.io/vbee-tts-297514/data
      context: data
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    # - image: viethung512/tts_training
    - image: us.gcr.io/vbee-tts-297514/training
      context: training
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: us.gcr.io/vbee-tts-297514/worker
      context: worker
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
