apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          # image: viethung512/tts_auth
          image: us.gcr.io/vbee-tts-297514/auth
          env:
            - name: PORT
              value: '4000'

            - name: MONGO_HOST
              value: '104.154.106.47'
            - name: MONGO_PORT
              value: '27017'
            - name: MONGO_DATABASE
              value: 'dev_tts_auth'
            - name: MONGO_USERNAME
              value: 'admin'
            - name: MONGO_PASSWORD
              value: 'admin123'

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: ROOT_USER_USERNAME
              value: 'admin'
            - name: ROOT_USER_EMAIL
              value: 'admin@test.com'
            - name: ROOT_USER_PHONE_NUMBER
              value: '0987654321'
            - name: ROOT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: root-password
                  key: ROOT_USER_PASSWORD

            - name: HOST_URL
              value: 'http://tts-api.hung97.com'
            - name: STATIC_HOST
              value: 'http://tts-static.hung97.com'

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'tts'

          resources:
            requests:
              cpu: '20m'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 4000
      targetPort: 4000
