name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: $GKE_SA_KEY
          project_id: $GKE_PROJECT
        env:
          GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
          GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

      - name: Configure Docker use gcloud command-line tool as a credential
        run: gcloud --quiet auth configure-docker

      - name: Get gcloud credentials
        run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        env:
          GKE_CLUSTER: tts-prod
          GKE_ZONE: southamerica-east1-b

      # Build the Docker image
      - name: Build docker image
        run: cd auth && docker build -t viethung512/tts_auth:$GITHUB_SHA .

      - name: Login to dockerhub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to dockerhub
        run: docker push "viethung512/auth:$GITHUB_SHA"

      - name: Restart auth-depl
        run: kubectl rollout restart deployment auth-depl
