name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configure Docker use gcloud command-line tool as a credential
        run: gcloud --quiet auth configure-docker

      - name: Get gcloud credentials
        run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        env:
          GKE_CLUSTER: tts-prod
          GKE_ZONE: southamerica-east1-b

      # Build the Docker image
      - name: Build docker image
        run: cd auth && docker build -t viethung512/tts_auth:$GITHUB_SHA .

      - name: Login to dockerhub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to dockerhub
        run: docker push "viethung512/tts_auth:$GITHUB_SHA"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          ./kustomize edit set image viethung512/tts_auth:TAG=viethung512/tts_auth:$GITHUB_SHA
          ./kustomize build . | kubectl apply -f infra/k8s-prod/auth-depl.yaml
          kubectl rollout restart deployment auth-depl

      # - name: Apply deployment
      #   run: kubectl apply -f infra/k8s-prod/auth-depl.yaml

      # - name: Restart auth-depl
      #   run: kubectl rollout restart deployment auth-depl
