name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: $GKE_SA_KEY
          project_id: $GKE_PROJECT
        env:
          GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
          GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

      - name: Configure Docker use gcloud command-line tool as a credential
        run: gcloud --quiet auth configure-docker

      - name: Get gcloud credentials
        run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        env:
          GKE_CLUSTER: tts-prod
          GKE_ZONE: southamerica-east1-b

      - name: Apply manifests
        run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
