export const sentenceTypes = {
  TYPE_BOOK: 'BOOK',
  TYPE_CALL_CENTER: 'CALL_CENTER',
  TYPE_DIALOG: 'DIALOG',
  TYPE_NEWS: 'NEWS',
  TYPE_STORY: 'STORY',
  TYPE_DIALOG_2: 'DIALOG_2',
};

export const sentenceStatus = {
  STATUS_INITIAL: 'INITIAL',
  STATUS_ASSIGNED: 'ASSIGNED',
  STATUS_SUBMITTED: 'SUBMITTED',
  STATUS_ERROR: 'ERROR',
  STATUS_APPROVED: 'APPROVED',
};
